// <auto-generated />
using System;
using E_Commerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce.Model.Hr.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments", "Hr");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            ManagerId = 5,
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("E_Commerce.Model.Hr.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees", "Hr");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FName = "Ahmed",
                            LName = "Ali"
                        },
                        new
                        {
                            Id = 2,
                            FName = "Mohammed",
                            LName = "Saeed"
                        },
                        new
                        {
                            Id = 3,
                            FName = "Youssef",
                            LName = "Khaled"
                        },
                        new
                        {
                            Id = 4,
                            FName = "Abdullah",
                            LName = "Ahmed"
                        },
                        new
                        {
                            Id = 5,
                            FName = "Sami",
                            LName = "Al-Otaibi"
                        },
                        new
                        {
                            Id = 6,
                            FName = "Khaled",
                            LName = "Mahmoud"
                        },
                        new
                        {
                            Id = 7,
                            FName = "Omar",
                            LName = "Al-Sheikh"
                        },
                        new
                        {
                            Id = 8,
                            FName = "Maher",
                            LName = "Youssef"
                        },
                        new
                        {
                            Id = 9,
                            FName = "Hussein",
                            LName = "Mostafa"
                        },
                        new
                        {
                            Id = 10,
                            FName = "Ali",
                            LName = "Hassan"
                        },
                        new
                        {
                            Id = 11,
                            FName = "Tariq",
                            LName = "Suleiman"
                        },
                        new
                        {
                            Id = 12,
                            FName = "Jamal",
                            LName = "Zaidan"
                        },
                        new
                        {
                            Id = 13,
                            FName = "Hamad",
                            LName = "Nasser"
                        },
                        new
                        {
                            Id = 14,
                            FName = "Khaled",
                            LName = "Amin"
                        },
                        new
                        {
                            Id = 15,
                            FName = "Adel",
                            LName = "Salem"
                        },
                        new
                        {
                            Id = 16,
                            FName = "Faisal",
                            LName = "Fahad"
                        },
                        new
                        {
                            Id = 17,
                            FName = "Saleh",
                            LName = "Abdulrahman"
                        },
                        new
                        {
                            Id = 18,
                            FName = "Badr",
                            LName = "Hassan"
                        },
                        new
                        {
                            Id = 19,
                            FName = "Marwan",
                            LName = "Ali"
                        },
                        new
                        {
                            Id = 20,
                            FName = "Yasser",
                            LName = "Mansour"
                        },
                        new
                        {
                            Id = 21,
                            FName = "Saad",
                            LName = "Hussein"
                        },
                        new
                        {
                            Id = 22,
                            FName = "Ziyad",
                            LName = "Tariq"
                        },
                        new
                        {
                            Id = 23,
                            FName = "Shadi",
                            LName = "Sameer"
                        },
                        new
                        {
                            Id = 24,
                            FName = "Salim",
                            LName = "Emad"
                        },
                        new
                        {
                            Id = 25,
                            FName = "Sami",
                            LName = "Jasim"
                        },
                        new
                        {
                            Id = 26,
                            FName = "Muneer",
                            LName = "Badr"
                        },
                        new
                        {
                            Id = 27,
                            FName = "Waleed",
                            LName = "Abdulrahim"
                        },
                        new
                        {
                            Id = 28,
                            FName = "Hazem",
                            LName = "Salim"
                        },
                        new
                        {
                            Id = 29,
                            FName = "Abdulmalik",
                            LName = "Saud"
                        },
                        new
                        {
                            Id = 30,
                            FName = "Imad",
                            LName = "Abdullah"
                        });
                });

            modelBuilder.Entity("E_Commerce.Model.Inventory.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories", "Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Toys"
                        });
                });

            modelBuilder.Entity("E_Commerce.Model.Inventory.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UrlImg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("categoryId");

                    b.ToTable("Products", "Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gaming Laptop",
                            Name = "Laptop",
                            Price = 999.99m,
                            Quantity = 50,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Latest Model",
                            Name = "Smartphone",
                            Price = 699.99m,
                            Quantity = 100,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Double Door",
                            Name = "Fridge",
                            Price = 799.99m,
                            Quantity = 30,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Digital Microwave",
                            Name = "Microwave",
                            Price = 149.99m,
                            Quantity = 25,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Leather Sofa",
                            Name = "Sofa",
                            Price = 599.99m,
                            Quantity = 10,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "Wooden Bookshelf",
                            Name = "Bookshelf",
                            Price = 79.99m,
                            Quantity = 15,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "Modern Lamp",
                            Name = "Table Lamp",
                            Price = 29.99m,
                            Quantity = 45,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ergonomic Chair",
                            Name = "Chair",
                            Price = 99.99m,
                            Quantity = 20,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Best Seller",
                            Name = "Novel",
                            Price = 19.99m,
                            Quantity = 200,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 4
                        },
                        new
                        {
                            Id = 10,
                            Description = "Educational",
                            Name = "Textbook",
                            Price = 59.99m,
                            Quantity = 80,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 4
                        },
                        new
                        {
                            Id = 11,
                            Description = "Cotton Shirt",
                            Name = "Shirt",
                            Price = 29.99m,
                            Quantity = 150,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 5
                        },
                        new
                        {
                            Id = 12,
                            Description = "Denim Jeans",
                            Name = "Jeans",
                            Price = 49.99m,
                            Quantity = 120,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 5
                        },
                        new
                        {
                            Id = 13,
                            Description = "Summer Dress",
                            Name = "Dress",
                            Price = 69.99m,
                            Quantity = 60,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 5
                        },
                        new
                        {
                            Id = 14,
                            Description = "Winter Jacket",
                            Name = "Jacket",
                            Price = 99.99m,
                            Quantity = 50,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 5
                        },
                        new
                        {
                            Id = 15,
                            Description = "Large Size",
                            Name = "Teddy Bear",
                            Price = 19.99m,
                            Quantity = 300,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 6
                        },
                        new
                        {
                            Id = 16,
                            Description = "Superhero Toy",
                            Name = "Action Figure",
                            Price = 29.99m,
                            Quantity = 200,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 6
                        },
                        new
                        {
                            Id = 17,
                            Description = "1000 Pieces",
                            Name = "Puzzle",
                            Price = 14.99m,
                            Quantity = 100,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 6
                        },
                        new
                        {
                            Id = 18,
                            Description = "Family Game",
                            Name = "Board Game",
                            Price = 39.99m,
                            Quantity = 70,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 6
                        },
                        new
                        {
                            Id = 19,
                            Description = "Remote Control Car",
                            Name = "Toy Car",
                            Price = 49.99m,
                            Quantity = 150,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 6
                        },
                        new
                        {
                            Id = 20,
                            Description = "Mini Drone",
                            Name = "Drone",
                            Price = 129.99m,
                            Quantity = 50,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 6
                        },
                        new
                        {
                            Id = 21,
                            Description = "High-speed Blender",
                            Name = "Blender",
                            Price = 89.99m,
                            Quantity = 40,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 2
                        },
                        new
                        {
                            Id = 22,
                            Description = "Electric Oven",
                            Name = "Oven",
                            Price = 299.99m,
                            Quantity = 20,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 2
                        },
                        new
                        {
                            Id = 23,
                            Description = "27-inch 4K Monitor",
                            Name = "Monitor",
                            Price = 399.99m,
                            Quantity = 15,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 1
                        },
                        new
                        {
                            Id = 24,
                            Description = "Mechanical Keyboard",
                            Name = "Keyboard",
                            Price = 79.99m,
                            Quantity = 70,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 1
                        },
                        new
                        {
                            Id = 25,
                            Description = "Wireless Mouse",
                            Name = "Mouse",
                            Price = 29.99m,
                            Quantity = 100,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 1
                        },
                        new
                        {
                            Id = 26,
                            Description = "Front Load",
                            Name = "Washing Machine",
                            Price = 699.99m,
                            Quantity = 10,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 2
                        },
                        new
                        {
                            Id = 27,
                            Description = "Electric Dryer",
                            Name = "Dryer",
                            Price = 599.99m,
                            Quantity = 8,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 2
                        },
                        new
                        {
                            Id = 28,
                            Description = "Digital Camera",
                            Name = "Camera",
                            Price = 499.99m,
                            Quantity = 25,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 1
                        },
                        new
                        {
                            Id = 29,
                            Description = "Noise Cancelling",
                            Name = "Headphones",
                            Price = 199.99m,
                            Quantity = 60,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 1
                        },
                        new
                        {
                            Id = 30,
                            Description = "10-inch Tablet",
                            Name = "Tablet",
                            Price = 299.99m,
                            Quantity = 50,
                            UrlImg = "https://www.gsascheduleservices.com/wp-content/uploads/2021/01/Empty-Box-min-300x300.png",
                            categoryId = 1
                        });
                });

            modelBuilder.Entity("E_Commerce.Model.UserMangement.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlImag")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg");

                    b.HasKey("Id");

                    b.ToTable("Users", "UserMangement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed.ali@example.com",
                            FName = "Ahmed",
                            LName = "Ali",
                            Password = "password1",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mohammed.saeed@example.com",
                            FName = "Mohammed",
                            LName = "Saeed",
                            Password = "password2",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Email = "yousef.khaled@example.com",
                            FName = "Yousef",
                            LName = "Khaled",
                            Password = "password3",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Email = "abdullah.omar@example.com",
                            FName = "Abdullah",
                            LName = "Omar",
                            Password = "password4",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Email = "omar.farouk@example.com",
                            FName = "Omar",
                            LName = "Farouk",
                            Password = "password5",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Email = "ali.hassan@example.com",
                            FName = "Ali",
                            LName = "Hassan",
                            Password = "password6",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Email = "hussein.mustafa@example.com",
                            FName = "Hussein",
                            LName = "Mustafa",
                            Password = "password7",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Email = "salim.ibrahim@example.com",
                            FName = "Salim",
                            LName = "Ibrahim",
                            Password = "password8",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Email = "fahd.mansour@example.com",
                            FName = "Fahd",
                            LName = "Mansour",
                            Password = "password9",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Email = "khalil.salah@example.com",
                            FName = "Khalil",
                            LName = "Salah",
                            Password = "password10",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Email = "tariq.abdullah@example.com",
                            FName = "Tariq",
                            LName = "Abdullah",
                            Password = "password11",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 12,
                            Email = "sami.zaid@example.com",
                            FName = "Sami",
                            LName = "Zaid",
                            Password = "password12",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 13,
                            Email = "mahmoud.fawaz@example.com",
                            FName = "Mahmoud",
                            LName = "Fawaz",
                            Password = "password13",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 14,
                            Email = "bilal.nasser@example.com",
                            FName = "Bilal",
                            LName = "Nasser",
                            Password = "password14",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 15,
                            Email = "mustafa.sayed@example.com",
                            FName = "Mustafa",
                            LName = "Sayed",
                            Password = "password15",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 16,
                            Email = "bassam.adel@example.com",
                            FName = "Bassam",
                            LName = "Adel",
                            Password = "password16",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 17,
                            Email = "amir.jamal@example.com",
                            FName = "Amir",
                            LName = "Jamal",
                            Password = "password17",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 18,
                            Email = "zaid.hussein@example.com",
                            FName = "Zaid",
                            LName = "Hussein",
                            Password = "password18",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 19,
                            Email = "nabil.othman@example.com",
                            FName = "Nabil",
                            LName = "Othman",
                            Password = "password19",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 20,
                            Email = "rami.anwar@example.com",
                            FName = "Rami",
                            LName = "Anwar",
                            Password = "password20",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 21,
                            Email = "jamil.qasim@example.com",
                            FName = "Jamil",
                            LName = "Qasim",
                            Password = "password21",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 22,
                            Email = "hadi.rashid@example.com",
                            FName = "Hadi",
                            LName = "Rashid",
                            Password = "password22",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 23,
                            Email = "walid.hamza@example.com",
                            FName = "Walid",
                            LName = "Hamza",
                            Password = "password23",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 24,
                            Email = "adnan.salim@example.com",
                            FName = "Adnan",
                            LName = "Salim",
                            Password = "password24",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 25,
                            Email = "anas.younes@example.com",
                            FName = "Anas",
                            LName = "Younes",
                            Password = "password25",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 26,
                            Email = "saif.shadi@example.com",
                            FName = "Saif",
                            LName = "Shadi",
                            Password = "password26",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 27,
                            Email = "othman.ziyad@example.com",
                            FName = "Othman",
                            LName = "Ziyad",
                            Password = "password27",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 28,
                            Email = "mounir.ghassan@example.com",
                            FName = "Mounir",
                            LName = "Ghassan",
                            Password = "password28",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 29,
                            Email = "kareem.ishaq@example.com",
                            FName = "Kareem",
                            LName = "Ishaq",
                            Password = "password29",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        },
                        new
                        {
                            Id = 30,
                            Email = "salah.firas@example.com",
                            FName = "Salah",
                            LName = "Firas",
                            Password = "password30",
                            UrlImag = "https://t3.ftcdn.net/jpg/03/53/11/00/360_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg"
                        });
                });

            modelBuilder.Entity("E_Commerce.Model.Hr.Department", b =>
                {
                    b.HasOne("E_Commerce.Model.Hr.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("E_Commerce.Model.Hr.Employee", b =>
                {
                    b.HasOne("E_Commerce.Model.Hr.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("E_Commerce.Model.Inventory.Product", b =>
                {
                    b.HasOne("E_Commerce.Model.Inventory.Category", "Category")
                        .WithMany("products")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("E_Commerce.Model.Hr.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("E_Commerce.Model.Inventory.Category", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
